version: "3.8"

services:
  dataB-primal:
    image: postgres:15
    networks:
      - overlay-1
    environment:
      POSTGRES_USER: postgressUser
      POSTGRES_DB: DataBas
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    configs:
      - source: pg_hba_primal_v12
        target: /etc/postgresql/pg_hba.conf
        uid: '999'
        gid: '999'
        mode: 0440
      - source: postgres_primal_v12
        target: /etc/postgresql/postgresql.conf
        uid: '999'
        gid: '999'
        mode: 0440
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U postgressUser -d DataBas"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    #  start_period: 120s

  dataB-replica:
    image: postgres:15
    networks:
      - overlay-1
    environment:
      POSTGRES_USER: postgressUser
      POSTGRES_DB: DataBas
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - db_password
    volumes:
      - db_data2:/var/lib/postgresql/data
    configs:
      - source: pg_hba_replica_v2
        target: /etc/postgresql/pg_hba.conf
        uid: '999'
        gid: '999'
        mode: 0440
      - source: postgres_replica_v4
        target: /etc/postgresql/postgresql.conf
        uid: '999'
        gid: '999'
        mode: 0440
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    #healthcheck:
     # test: ["CMD-SHELL", "pg_isready -U postgressUser -d DataBas"]
      #interval: 10s
     # timeout: 5s
     # retries: 5
     # start_period: 120s





  pgadmin:
    image: dpage/pgadmin4:9.8
    networks:
      - overlay-1
    ports:
       - 5050:80 # Только этот порт открыт наружу [5]
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@axenta.tech
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/db_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    secrets:
      - db_password
    configs:
      - source: pgadmin_servers_v1
        target: /pgadmin4/servers.json
        uid: '505' 
        gid: '505'
        mode: 0444
    deploy:
      replicas: 1
  #  healthcheck:
  #    test: ["CMD-SHELL", "timeout 1s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
  #    start_period: 30s

networks:
  overlay-1:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1400 # Решает проблему "бесконечной загрузки" в Swarm

volumes:
  db_data:
  db_data2:
  pgadmin_data:

secrets:
  db_password:
    external: true


configs:
  pg_hba_primal_v12:
    file: ./pg_confs/primal/pg_hba.conf
  postgres_primal_v12:
    file: ./pg_confs/primal/postgresql.conf
  pgadmin_servers_v1:
    file: ./servers.json
  pg_hba_replica_v2:
    file: ./pg_confs/replica/pg_hba.conf
  postgres_replica_v4:
    file: ./pg_confs/replica/postgresql.conf

