local   all             all                                     trust
host    all             all             0.0.0.0/0               trust

#Данные настроки критически небезопастны. Выбраны времмено для отладки соединения c pgAdmin.