data_directory = '/var/lib/postgresql/data/pgdata'
primary_conninfo = 'host=DevOps_dataB-primal port=5432 user=postgressUser password=postgressUser'
listen_addresses = '*'
port = 5432
hot_standby = on
hot_standby_feedback = on
max_standby_streaming_delay = 5s
wal_receiver_timeout = 1s

# Только для чтения
default_transaction_read_only = on
transaction_read_only = on

shared_buffers = 128MB



